project:
  type: book

lang: ko-KR

book:
  title: "공부하는 언론인을 위한 R기반 데이터 저널리즘"  
  author: "박찬경(경북대학교)·사영준(서강대학교)"
  date: "9/3/2023"
  chapters:
    - index.qmd
    - journalism.qmd
    - appendix-journalism.qmd
    - ds.qmd
    - install.qmd
    - quarto.qmd
    - basic.qmd
    - tidy.qmd
    - manipulate.qmd
    - summarise.qmd
    - visualize.qmd
    - retrieval.qmd
    - story.qmd
    - story2.qmd
    - spatial.qmd
    - appendix-install.qmd
    - appendix-code.qmd

#bibliography: references.bib

format:
  html:
    theme: superhero
  pdf:
    documentclass: report
    #fontfamily: Batang
    include-in-header:
      - text: 
          \usepackage{layouts}
          \usepackage{setspace}
          \onehalfspacing
          \usepackage{fvextra}
          \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
    include-before-body:
      - text: 
          \RecustomVerbatimEnvironment{verbatim}{Verbatim}{showspaces = false, showtabs = false, breaksymbolleft={}, breaklines}

knitr:
  opts_chunk:
    fig.showtext: TRUE

editor: visual

#mainfont: Batang
#sansfont: Batang
#monofont: Batang

