# 서문 {.unnumbered}
저널리즘이 위기라는 이야기가 들려온지 벌써 십수년이 지났습니다. 그간 디지털화, 소비자 컨텐츠 발굴 등 몇가지 혁신이 있었지만, 지금 돌이켜보면 많은 시도들이 인터넷의 정보 유통 구조 변화를 쫓아가는 방식으로 귀결되면서 결국 미디어가 자생력을 잃고 플랫폼 기업들에게 수익을 내맡기는 결과를 낳고 말았습니다. 그 때문에 서구의 많은 언론사들은 미디어의 본질인 독보적인 콘텐츠의 생산과 이를 통한 독자적인 수익 구조를 추구하는 방식으로 회귀하고 있습니다.

독자적 수익을 창출할 수 있는 독보적 컨텐츠의 생산. 이것은 어쩌면 그간 이어온 한국의 미디어 혁신에서 가장 간과되었던 것들 중 하나입니다. 누구나 취재와 출판, 유통이 가능한 시대에 독보적 컨텐츠는 어떻게 가능하고, 보도의 전문성은 어떻게 확보될 수 있을까요? 데이터 저널리즘은 그에 대한 대답 중 하나 입니다. 대형 언론사들 뿐만 아니라, 미디어 스타트업, 지역 언론사, 제3세계 언론사, 그리고 탐사 저널리즘 등은 그들을 활성화시키기 위한 오래된 숙제의 해법으로 대중들은 접근할 수 사실을 발굴하기 보다는 이미 접근 가능한 대량의 데이터들을 연결하고 분석하고, 전달하는 과정을 통해 새로운 통찰을 전달하는 '데이터 저널리즘'에 주목하고 있습니다. 

문제는 데이터 저널리즘은 기자, 언론사에게 새로운 전문성을 요구한다는 것입니다. 발로 뛰면서 집요하게 진실을 추적하는 전통적인 기자에게 요구되는 덕목과 자질과 달리, 데이터 저널리즘은 책상 앞에서 앉아 데이터들을 발굴하고, 그 안에서 숨어있는 메시지를 찾아내는 능력을 요구합니다. 속보 경쟁을 해야하는 언론인들에게 이러한 전문성을 발휘하는 것도, 그리고 그러한 전문성을 새로이 습득하기 위한 학습 과정도 사치처럼 여겨질 것입니다.

본 교재는 극한의 취재와 보도 경쟁에 내몰려 있지만, 위기에 빠진 언론을 위한 다음 스텝을 고민하는, 공부하는 기자들을 위한 데이터저널리즘 교재 입니다. 본 교재는 데이터 저널리즘에 경험이 없는 언론인들이 가능한 짬을 내어 독학하는 상황을 가정하여 만들었습니다. 이를 위해 다음과 같은 특징을 가지고 있습니다.

- 첫째, 온라인으로 만들어 누구나 쉽게 접근할 수 있도록 하였습니다.

- 둘째, 실제 보도 상황에 근접한 빅데이터, API를 통해 획득한 비정형 데이터를 이용한 데이터 분석을 바로 시작할 수 있는 예제를 최대한 반영하였습니다.

- 셋째, R을 이용하였습니다. 최대한의 유연성을 제공하는 컴퓨터 언어이면서도 무료이고, 간단한 문법을 가지고 있는 데이터 저널리즘 산업의 표준적인 언어 중 하나입니다.

- 넷째, 데이터의 분석에만 초점을 맞추지 않았습니다. 데이터 저널리즘의 필요성, 전통적 저널리즘과의 차별성에 주목하였고, 데이터 스토리텔링의 관점에서 필요한 몇 가지 영상 심리학 이론, 시각화 기법등을 구현하는 법에 대해서도 이야기하였습니다. 그리고 배포까지 염두에 두어 바로 웹페이지를 생산할 수 있는 컴퓨팅 환경을 기본으로 사용합니다. 

그렇다고 해서, 이 교재는 완전히 문외한인 언론인만을 위한 것은 아닙니다. 다양한 학습 경험이 있는 언론인들이 유연성 있게 활용할 수 있도록 하기 위해, 각 챕터를 난이도 별로 구분해서 작성하고자 노력했습니다. 이를 최대한 활용하기 위해, 다음과 같은 수준별 학습        방법을 권합니다. 

- R또는 프로그래밍이 완전히 처음인 독자: 부록 install 부터.

- R을 접해 보았고 프로그래밍에 대한 초보적인 사전지식이 있으나 거의 활용해보지 않은 독자: 부록을 건너뛰고 처음부터

- R을 활용해 본 경험이 있는 독자: install을 건너뛸 것.

- 프로그래밍 경험이 있으나, 데이터 저널리즘에 적용하는 방식에 대해 궁금한 독자: data science, journalism, data storytelling 부분

그간 데이터 저널리즘에 대한 지식은 여기저기 흩어져 있어, 학습을 원하는 독자들은 조각난 지식들을 모으는데에서 부터 시작해야 했고, 따라서 학습을 포기하기 일수였습니다. 뉴스타파에서 나온 좋은 교재가 있지만, 파이썬이라는 휼륭하지만 비교적 비전공자에게 접근성이 떨어지는 프로그램 언어를 사용했고, 분석 이외의 부분에 크게 주목하지 않았습니다. 이는 해외의 경우에도 크게 다르지 않습니다. 이 교재는 가능한 이론적 부분, 디자인 취재 부분과 프로그래밍에 관해 그동안 쌓인 지식을 최대한 모두 다루려 노력하였습니다. 

또 하나 매우 중요한 점 중 하나는 이 교재가 오픈 텍스트북을 지향한다는 것입니다. 첫 삽은 제가 뜨지만 이를 github에 공개하고, 데이터 저널리즘을 가르치는 강의자들이 자유롭게 내용을 업데이트, 보완 할 수 있도록 하려고 합니다. 

이러한 작업을 가능하게 해 준 언론재단 본부장, 이민규 과장께 감사합니다. 그리고 관련된 여러 행정 처리를 도와준 경북대학교 고서영, 이신애 학생에게 감사를 드립니다. 특히 고서영 학생은 이 교재에 포함된 많은 삽화를 고생스럽게 그려주었습니다. 

이 교재를 계기로 데이터 저널리즘의 교재 가뭄 현상을 해소하고, 앞으로 더 많은, 좋은 교재가 나오기를, 더 나아가 데이터 저널리즘에 대한 접근성이 증가하기를 기대해 ㄷ봅니다. 

여기에서 교재를 읽는 일종으 구조도를 알려주기!
- 설치도 모르는 사람
- 프로그래밍을 조금이라도 겪어봤지만, R은 써보지 않은 사람
- R을 써 보았지만, Tidyverse를 이용한 최근 프로그래밍 트렌드에 익숙지 않은 사람
- Tidyverse도 써 보았으나, 이를 보도에 쓸 생각을 해 보지는 않은 사람.

추후 작성

R로 분석을 하는 것이 아니라, R을 이용해 기사를 '작성' 한다는 관점!


설명은 항상 실습을 위한 것부터 -> 그 다음 이론적인 설명으로...

이 웹사이트는 지역 언론인을 위한 개발 사이트 입니다. 
donorschoose.org data와 스포츠, 공공데이터 이용.
언어로는 R을 이용할 것입니다. - 상대적으로 쉽고, - 공짜고, - 해외 데이터 저널리즘 커뮤니티에서 사실상 표준으로 사용되고 있습니다.


R은 배포까지 가능!

R이 있으면 데이터 수집부터 배포까지 - 이론적으로는 어떠한 투자도 필요 없이 1인 미디어가 가능한 것.


https://github.com/fivethirtyeight https://github.com/TheEconomist

-   좋은 IDE를 가지고 있고
-   바로 온라인으로 publish할 수 있는 기술이 잘 발달되어 있습니다 (공동 프로젝트 가능)
    -   이 책 역시 같은 방식을 이용해 만들어지고 있습니다.


복잡한 것들을 최대한 늦게 필요할 때 가르치는 것을 목표로 합니다. 빅데이터 또는 주어진 관찰 데이터를 예시로 삼습니다. 

저널리즘 - 시각화/데이터 스토리텔링 이론 등등

기초와 고급 토픽 구분

모든 단원 시작할 때 필요한 패키지부터.

## To-do's
- 데이터 시각화 하기 2 (Optional): Storytelling
    -   웹 프로그래밍의 응용
    -   HTML, CSS 이해
- 공공 데이터 이용하기
    -   API 이해하기
    -   XML, JSON 이해하기
    -   For-loop, function 이해하기
- 스크래이핑
    -   고급 스크레이핑에 대한 이야기.
- 고급 토픽: 공간 데이터 이용하기 + 시각화.
- 고급 토픽: 예측을 이용한 보도
    -   주식 집값이 보편적인 예시이지만,
    -   스포츠가 더 plausible한 예시.
- 고급 토픽: Interactive Design
- 데이터 배포하기에 대한 이해
    -   HTML
    -   Markdown
    -   Pandoc
    -   Quarto
    -   Github

